### ISSUE TITLE
putInVehicle only 1 seat?

### ISSUE THREAD

**Issue by JaroSound** [esx-framework/esx_policejob#32]
Why i can put only 1 player in a police car?

**Comment by ElPumpo** [comment]
It depends on the vehicle, the funtion works just fine - reopen if the issue still is there.

**Comment by JaroSound** [comment]
The issue is still there on all vehicles.

**Comment by StasiekESX** [comment]
Sill here

**Comment by Fluxiitis** [comment]
Any fix?

**Comment by GrizzlyRP** [comment]
Issue still there... @Fluxiitis How did you fix it?

**Comment by ItzKevin01** [comment]
already a solution for this?
