### ISSUE TITLE
Can't buy vehicles

### ISSUE THREAD

**Issue by PsydoV2** [esx-framework/esx_policejob#33]
If i buy a car it takes the money but i don't get the car

**Comment by MoskalykA** [comment]
Hi, what's your ESX version?

**Comment by PsydoV2** [comment]
1.8.5

**Comment by MoskalykA** [comment]
> 1.8.5

You might want to try updating ESX, the latest version is 1.10.1

**Comment by PsydoV2** [comment]
[     39985] [b2802_GTAProce]             MainThrd/ [^1ERROR^7] Resource ^5LAMCDispatch^7 Used the ^5getSharedObject^7 Event, this event ^1no longer exists!^7 Visit https://documentation.esx-framework.org/tutorials/tutorials-esx/sharedevent for how to fix!

Then that happens

**Comment by PsydoV2** [comment]
hell nah

**Comment by PsydoV2** [comment]
Is it possible to get an older version of the police job which works with my extendet version?

**Comment by NikartikTheBear** [comment]
Just look for older versions in the repo if you need that but it severely advised against, why would you want less functionalities, less security and more biggy code

**Comment by Gellipapa** [comment]
Hi! @PsydoV2 Please update latest version your esx, we don't support old version anymore.
