### ISSUE TITLE
weapons

### ISSUE THREAD

**Issue by Sarunas2024** [esx-framework/esx_policejob#36]
when i press to take out weapon from armory wont do nothing
geting this error 

[script:esx_policejob] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:479: attempt to concatenate a nil value (local 'err')
[script:esx_policejob] > handler (@esx_datastore/server/main.lua:66)
[script:esx_policejob] > ref (@esx_policejob/server/main.lua:230)
[script:esx_policejob] > handler (@es_extended/server/modules/callback.lua:19)
[script:esx_datastore] SCRIPT ERROR: error object is not a string
[script:esx_datastore] > ref (@esx_policejob/server/main.lua:230)
[script:esx_datastore] > handler (@es_extended/server/modules/callback.lua:19)
[script:esx_datastore] SCRIPT ERROR: @esx_datastore/server/classes/datastore.lua:34: attempt to index a nil value (local 'obj')
[script:esx_datastore] > ref (@esx_datastore/server/classes/datastore.lua:34)
[script:esx_datastore] > ref (@esx_policejob/server/main.lua:231)
[script:esx_datastore] > handler (@esx_datastore/server/main.lua:66)
[script:esx_datastore] > ref (@esx_policejob/server/main.lua:230)
[script:esx_datastore] > handler (@es_extended/server/modules/callback.lua:19)

**Comment by Gellipapa** [comment]
@Sarunas2024 Hi! Please use the latest es_extended and esx resources and the problem is solved. We don't support old core or old scripts.
