### ISSUE TITLE
Armory duping

### ISSUE THREAD

**Issue by XvenDeR** [esx-framework/esx_policejob#367]
1. needs 2 players
2. both open armory to take stock
3. both takes same item
4. item dublicates....

any fix for this?

EDIT: Solution by @Tinky124 fixed by checking is player to close to you when opening armory
```lua
local closestPlayer, closestDistance = ESX.Game.GetClosestPlayer()
if closestPlayer ~= -1 and closestDistance > 2.0 then
     OpenArmoryMenu(CurrentActionData.station)
elseif GetNumberOfPlayers() == 1 then
     OpenArmoryMenu(CurrentActionData.station)
else
    ESX.ShowNotification('~y~You cant open armory, ~r~because other player is too close!')
end
```

**Comment by XvenDeR** [comment]
Closed?

**Comment by ElPumpo** [comment]
Misclick

**Comment by Tinky124** [comment]
@XvenDeR item or weapon?

**Comment by XvenDeR** [comment]
> @XvenDeR item or weapon?

ooof, weapons for sure, items probably too, not sure.

**Comment by SliderKP** [comment]
Same bug, any way to solve? @XvenDeR

**Comment by XvenDeR** [comment]
Nope.

**Comment by HumanTree92** [comment]
Could set it so only 1 person can be in the menu at a time.

**Comment by SliderKP** [comment]
@HumanTree92 yes is a good idea, for the moment i reduced the size of blip...

**Comment by Silent-dawn** [comment]
> @HumanTree92 yes is a good idea, for the moment i reduced the size of blip...
> 
> can you show me a way to accept only 1 person in the menu ?

You'd need to have a handle that checks for someone accessing the menu, and then add logic for denying access until the previous user exits, reporting you're done using it from the client to the server, server setting variable to 0 to allow someone else to connect, repeat. Takes some client and server side code to work, but it is possible.

**Comment by Marfru** [comment]
Yeah this is a pretty common issue in servers. Because most servers re-use the base of esx_policejob to create mafias. And yeah, economy is unstable

**Comment by rowk1337** [comment]
Anyone fixed this ? :(

**Comment by raminhos** [comment]
Any fix by now ?

**Comment by XvenDeR** [comment]
Fix is to not use armories. :D

**Comment by Tinky124** [comment]
@XvenDeR No i fixed my armory by checking is player to close to you when opening armory
```lua
local closestPlayer, closestDistance = ESX.Game.GetClosestPlayer()
  if closestPlayer ~= -1 and closestDistance > 2.0 then
     OpenArmoryMenu(CurrentActionData.station)
elseif GetNumberOfPlayers() == 1 then
     OpenArmoryMenu(CurrentActionData.station)
else
    ESX.ShowNotification('~y~You cant open armory, ~r~because other player is too close!')
end
```

**Comment by Tinky124** [comment]
Also i fixed when 2 players try to search player

**Comment by raminhos** [comment]
Thank you so much. I will try and give feedback.

**Comment by raminhos** [comment]
BTW, i use same script for gangs. but one gang can't confiscate. any thoughts ?? Thank you

**Comment by Rev0lt69** [comment]
elseif CurrentAction == 'menu_armory' then
					local closestPlayer, closestDistance = ESX.Game.GetClosestPlayer()
                    if closestPlayer ~= -1 and closestDistance > 2.0 then
						OpenArmoryMenu(CurrentActionData.station)
					elseif GetNumberOfPlayers() == 1 then
						OpenArmoryMenu(CurrentActionData.station)
					else
						ESX.ShowNotification('~y~You cant open armory, ~r~because other player is too close!')
					end

I did the same thing bus it doesnt work

**Comment by Rev0lt69** [comment]
elseif CurrentAction == 'menu_armory' then
					local closestPlayer, closestDistance = ESX.Game.GetClosestPlayer()
                    if closestPlayer ~= -1 and closestDistance > 2.0 then
						OpenArmoryMenu(CurrentActionData.station)
					elseif GetNumberOfPlayers() == 1 then
						OpenArmoryMenu(CurrentActionData.station)
					else
						ESX.ShowNotification('~y~You cant open armory, ~r~because other player is too close!')
					end

I did the same thing but it doesn't work

**Comment by Rev0lt69** [comment]
> @XvenDeR No i fixed my armory by checking is player to close to you when opening armory
> 
> ```lua
> local closestPlayer, closestDistance = ESX.Game.GetClosestPlayer()
>   if closestPlayer ~= -1 and closestDistance > 2.0 then
>      OpenArmoryMenu(CurrentActionData.station)
> elseif GetNumberOfPlayers() == 1 then
>      OpenArmoryMenu(CurrentActionData.station)
> else
>     ESX.ShowNotification('~y~You cant open armory, ~r~because other player is too close!')
> end
> ```

			elseif CurrentAction == 'menu_armory' then
				local closestPlayer, closestDistance = ESX.Game.GetClosestPlayer()
                if closestPlayer ~= -1 and closestDistance > 2.0 then
					OpenArmoryMenu(CurrentActionData.station)
				elseif GetNumberOfPlayers() == 1 then
					OpenArmoryMenu(CurrentActionData.station)
				else
					ESX.ShowNotification('~y~You cant open armory, ~r~because other player is too close!')
				end


I did the same thing but it doesn't work

**Comment by XvenDeR** [comment]
It does.

**Comment by Rev0lt69** [comment]
> It does.

its the same with mine?because mine its not working

**Comment by XvenDeR** [comment]
Then you did something wrong.

**Comment by raminhos** [comment]
if CurrentAction == 'menu_armory' then

          -- ADICIONEI ISTO!!!
          local closestPlayer, closestDistance = ESX.Game.GetClosestPlayer()
          if closestPlayer ~= -1 and closestDistance > 2.0 then
            OpenArmoryMenu(CurrentActionData.station)
          elseif GetNumberOfPlayers() == 1 then
            OpenArmoryMenu(CurrentActionData.station)
          else
            ESX.ShowNotification('~y~Cuidado!! Tens alguém muito perto a ver o que tens no armário!!!')
          end
		  
          --OpenArmoryMenu(CurrentActionData.station)
        
        end

**Comment by Tinky124** [comment]
It is working too many people doesnt know how to put this code, LUL @XvenDeR

**Comment by XvenDeR** [comment]
It is, have tested it myself, good solution.

**Comment by raminhos** [comment]
> Also i fixed when 2 players try to search player

I forced negative on databse so i can see who try to cheat
