### ISSUE TITLE
Missing impound implementation

### ISSUE THREAD

**Issue by sandor-molnar** [esx-framework/esx_policejob#44]
https://github.com/esx-framework/esx_policejob/blob/main/client/main.lua#L1587
```lua
-- TODO
--   - return to garage if owned
--   - message owner that his vehicle has been impounded
```

**Comment by Gellipapa** [comment]
@sandor-molnar Hi! We are sorry but at the moment this will not be implemented because we are working on something else and it will be rewritten, so we will not develop this TODO for more than a year.

**Comment by sandor-molnar** [comment]
That's okay, though it would be nice to at least remove the TODO code from there :D Maybe adding a message to somewhere to notify devs that this feature is not implemented?
