### ISSUE TITLE
Unable to buy vehicle as Police

### ISSUE THREAD

**Issue by DevDokus** [esx-framework/esx_policejob#442]
Hey guys.. When i try to buy a vehicle i am getting the error that i am not authorized to buy that vehicle, while i am the boss of the station and having the perms.  Does anyone know what and why this is happening ? https://prnt.sc/sdoins

![image](https://user-images.githubusercontent.com/49053928/81474153-ca036a00-9203-11ea-9663-34e7d8f9fab3.png)

**Comment by IThinkImGood** [comment]
i have the same problem, did you find a fix?

**Comment by AgenChicken24** [comment]
It is not an error. Its because as boss you don't have any vehicles in the config 
![image](https://user-images.githubusercontent.com/64702468/92705713-99bc0b80-f35c-11ea-818a-d5cd60b9a9e8.png)

**Comment by NickKaz07** [comment]
This works!
