### ISSUE TITLE
Shop names

### ISSUE THREAD

**Issue by frankiec05** [esx-framework/esx_policejob#485]
How do I change the name of the vehicle?

![image](https://user-images.githubusercontent.com/68263870/89365421-6dd8a680-d689-11ea-8e5c-fa4d9832873e.png)
Is there a way to change NULL to a vehicle name?

**Comment by MiguelJe** [comment]
humm what makes you think this is a esx_policejob script question  dude ?

**Comment by frankiec05** [comment]
It is apart of the script you can enable it and add the vehicles, all I'm trying to do is change NULL to a vehicle name also if I scroll down the list of vehicles the menu for vehicle shop stops working, and I have to rejoin to do it. I just want it changed. You think its not a thing? The vehicle shop is a esx_policejob addon. Its built in.

**Comment by iNauj** [comment]
i have a same problem... when i add an addon car

**Comment by HumanTree92** [comment]
Go to FiveM & search How to setup vehicle_names.lua

**Comment by rocket5115** [comment]
in my case i needed to swap from (example)
officer = {
			{model = 'police3', price = 20000}
		},

officer = {
		{
			model = 'police3',
			label = 'Police Interceptor'
		}
	},

**Comment by frankiec05** [comment]
Email me if you want the script I created one my self email me and I will give it to you for free.

hollywoodliferp@gmail.com
