### ISSUE TITLE
SCRIPT ERROR: @esx_service/server/main.lua:10: bad argument #1 to 'pairs' (table expected, got nil)

### ISSUE THREAD

**Issue by Em1tSan** [esx-framework/esx_policejob#505]
When using the most recent version (from the master branch) when trying to put on a uniform in the locker room, an error appears in the server console, the uniform is not worn:

`SCRIPT ERROR: @esx_service/server/main.lua:10: bad argument #1 to 'pairs' (table expected, got nil)
> GetInServiceCount (@esx_service/server/main.lua:10)
> ref (@esx_service/server/main.lua:39)
> TriggerServerCallback (@extendedmode/server/functions.lua:160)
> handler (@extendedmode/server/common.lua:172)`

This problem is not observed when using version 1.3.0.

**Comment by Cactusje** [comment]
Same here

**Comment by haydenb94** [comment]
Anyone get this sorted? im having the same issue.

**Comment by graetz** [comment]
Change in `esx_policejob/client/main.lua`
`if Config.MaxInService == -1 then`
to
`if Config.MaxInService ~= -1 then`

and in `config.lua` `Config.MaxInService` change from -1 to something like 10.

**Comment by itschip** [comment]
This is a ExM (extendedmode) question/issue.

**Comment by faraonnn** [comment]
graerz FIXED!!! THX
