### ISSUE TITLE
Player blips not showing up with infinity.

### ISSUE THREAD

**Issue by OwnerDevSoviet** [esx-framework/esx_policejob#507]
Helllo, I have switched to onesync infinity and when a player it outside of the instance it doesnt display their location anymore. Can this be either added or maybe the fix posted here? I have seen it asked in a few places but here. Thank you for your time!

**Comment by GRZ-D3V** [comment]
The oneSYNC system is that FiveM separates the map into small areas, so anything that is not in your area you will not be able to see. Welcome to the 128 players+ / server
