### ISSUE TITLE
Update requirements

### ISSUE THREAD

**Issue by joaopedroo5** [esx-framework/esx_policejob#510]
While checking the code I came across with this line:
```
TriggerEvent('esx_status:getStatus', target, 'drunk', function(status)
	if status then
		data.drunk = ESX.Math.Round(status.percent)
	end
end)
```
Maybe you should add [esx_status](https://github.com/esx-framework/esx_status) the [README.md](https://github.com/esx-framework/esx_policejob/blob/master/README.md) so people know the script support it.

Personal quote:
> I've read a lot of your code and enjoy it, but you're missing a lot of documentation or even a little of information so people know what they can expect from the projects.
> Keep the good job =)

**Comment by itschip** [comment]
Maybe you should send a PR? 🦖

**Comment by joaopedroo5** [comment]
#516
