### ISSUE TITLE
 Rank spaces

### ISSUE THREAD

**Issue by UrgingGamer** [esx-framework/esx_policejob#525]
Hi! I wanted to add spaces to my Police ranks, but it fails. How can I add them?

Photo of the Ranks:

https://i.imgur.com/01QqJ59.png

Error on Console:

https://i.imgur.com/1zcigX7.png

**Comment by HumanTree92** [comment]
you must do something like police_chief

**Comment by UrgingGamer** [comment]
the _ is for the spaces?

**Comment by HumanTree92** [comment]
you can't do spaces. so for example the what i did for some of my police ranks is set the name as plcolonel and for the label its Lt Colonel

**Comment by UrgingGamer** [comment]
Ok. I'm getting another error, but I don't know how to fix them

Code:
https://i.imgur.com/R1iRoik.png

Console Photo:
https://i.imgur.com/CDYIo0f.png
