### ISSUE TITLE
CustomPeds

### ISSUE THREAD

**Issue by MaxiC-UADE** [esx-framework/esx_policejob#55]
Hi, custom peds are not working.

**Comment by Gellipapa** [comment]
Hi! @MaxiC-UADE Any error message or can you  send me video?

**Comment by MaxiC-UADE** [comment]
> Hi! @MaxiC-UADE Any error message or can you send me video?

Hello, i manage to fix it by myself, it was a mistake i made while trying change from ESX.OpenContext to ESX.UI.Menu.Open, All elements were as value but they must be like Uniform excepting 'citizen_wear' so i just change that and it works now.

Thanks anyway
